name: 'retail_ops_intelligence'
version: '1.0.0'
config-version: 2

profile: 'retail_ops'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_ops_intelligence:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      core:
        +materialized: table
      business:
        +materialized: table

seeds:
  retail_ops_intelligence:
    +enabled: false
    +schema: raw

tests:
  retail_ops_intelligence:
    data_quality:
      +severity: warn
    business_logic:
      +severity: error